### ISSUE TITLE
ValueError: 'UNKNOWN' is not a valid StorageType

### ISSUE THREAD

**Issue by kk7ds** [briis/pyunifiprotect#214]
I'm using the docker container (image hash 0824181c17ef) to run the tool, and I suddenly started getting this error when I try to access protect (2.1.1), specifically showing one or all cameras:

```
Traceback (most recent call last):
  File "/usr/local/bin/unifi-protect", line 8, in <module>
    sys.exit(start())
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/__main__.py", line 18, in start
    app()
  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/cli/__init__.py", line 121, in main
    loop.run_until_complete(update())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/cli/__init__.py", line 117, in update
    protect._bootstrap = await protect.get_bootstrap()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/api.py", line 781, in get_bootstrap
    return Bootstrap.from_unifi_dict(**data, api=self)
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/data/base.py", line 114, in from_unifi_dict
    data = cls.unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/data/bootstrap.py", line 184, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/data/base.py", line 336, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj(data[key], unifi_objs[key], api)
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/data/base.py", line 275, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/data/nvr.py", line 762, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/data/base.py", line 715, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/data/base.py", line 336, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj(data[key], unifi_objs[key], api)
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/data/base.py", line 275, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/data/base.py", line 336, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj(data[key], unifi_objs[key], api)
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/data/base.py", line 275, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/data/base.py", line 329, in unifi_dict_to_dict
    data[key] = convert_unifi_data(data[key], cls.__fields__[key])
  File "/usr/local/lib/python3.10/site-packages/pyunifiprotect/utils.py", line 189, in convert_unifi_data
    value = field.type_(value)
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'UNKNOWN' is not a valid StorageType
```

**Comment by AngellusMortis** [comment]
Some questions:

* What console are you using? 
* What is the firmware version for your console?
* What kind of storage are you using for your console?

**Comment by AngellusMortis** [comment]
Can you go to `/proxy/protect/api/nvr` on your console and give me the `systemInfo` property? It should look something like this:

```json
"systemInfo":{"cpu":{"averageLoad":4.25,"temperature":72},"memory":{"available":6224076,"free":86176,"total":8163012},"storage":{"available":19139496955904,"isRecycling":false,"size":95570817662976,"type":"raid","used":72273402355712,"devices":[{"model":"ST16000VE000-2L2103","size":16000900661248,"healthy":true},{"model":"ST16000VE000-2L2103","size":16000900661248,"healthy":true},{"model":"ST16000VE000-2L2103","size":16000900661248,"healthy":true},{"model":"ST16000VE000-2L2103","size":16000900661248,"healthy":true},{"model":"ST16000VE000-2L2103","size":16000900661248,"healthy":true},{"model":"ST16000VE002-3BR101","size":16000900661248,"healthy":true},{"model":"ST16000VE000-2L2103","size":16000900661248,"healthy":true}]}
```

Obviously, mine is a lot longer since I have 7 full drives in the UNVR Pro.

**Comment by kk7ds** [comment]
```
"systemInfo": {
    "cpu": null,
    "memory": null,
    "storage": {
      "available": 0,
      "isRecycling": false,
      "size": 0,
      "type": "UNKNOWN",
      "used": 0,
      "devices": []
    },
    "ustorage": null,
    "tmpfs": {
      "available": 243724,
      "total": 262144,
      "used": 18420,
      "path": "/var/opt/unifi-protect/tmp"
    }
  },
```

Hmm that's looking weird, huh? I did just upgrade protect a week or so ago, but the ValueError just started popping up in the last 12 hours.

**Comment by AngellusMortis** [comment]
Is your UniFi Protect actually showing a disk? Is it recording footage?

**Comment by kk7ds** [comment]
It is recording just fine and I can see actual recordings from the last 12 hours (which is the problematic period) no problem. However, I do see a new "None" with a warning symbol on the storage status and the pop-up says "HDD is required to record video".

So, hmm, maybe I've got an issue here. Sigh, ubnt.

So I'll go poke at that a bit and maybe this issue should turn into catching UNKNOWN and reporting some more useful error? Thanks for the help.

**Comment by kk7ds** [comment]
BTW, the disk is still there and smartctl says it's healthy, so I'm guessing something with unifi is confused:

```
root@unifi:~# df -h /srv
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda4       878G  814G   65G  93% /srv
```

**Comment by AngellusMortis** [comment]
Yeah, I need to still handle the "UNKNOWN" state, but it definetely looks like something is wrong with your console.

**Comment by kk7ds** [comment]
Yeah, seems so. Thanks for the hint, I'll go chase that.

**Comment by kk7ds** [comment]
A reboot now shows 942G where it said "None: HDD required" before. All the recordings continue to play from before, during and after. Also systemInfo looks correct now. Doesn't inspire faith in this device or ubnt, but alas.

So, sorry for the noise, I guess I should have "turned it off and back on" first, but since I was hitting the cameras API and getting an error, I figured it was something with the tool and didn't even consider anything related to the disk :)
