### ISSUE TITLE
Local variable `image_width` referenced before assignment

### ISSUE THREAD

**Issue by andrew-codes** [briis/pyunifiprotect#28]
I think this still appears to be an issue for me when running via the UnifiProtect Home Assistant custom integration. I'm running the master version of the UnfiProtect, which appears to be using the latest version of this repo, `0.30.18`, seen [here](https://github.com/briis/unifiprotect/blob/master/custom_components/unifiprotect/manifest.json#L8). Although the error message is surfacing in the UnifiProtect custom integration, I think the root cause is coming from this repo's code base.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 249, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home-automation/k8s/home-assistant/home-assistant-config/custom_components/unifiprotect/__init__.py", line 99, in async_setup_entry
    await protect_data.async_setup()
  File "/home-automation/k8s/home-assistant/home-assistant-config/custom_components/unifiprotect/data.py", line 32, in async_setup
    await self.async_refresh()
  File "/home-automation/k8s/home-assistant/home-assistant-config/custom_components/unifiprotect/data.py", line 48, in async_refresh
    await self._protectserver.update(
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 123, in update
    await self._get_device_list(not self.ws_connection)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 314, in _get_device_list
    self._process_cameras_json(json_response, server_id, include_events)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 335, in _process_cameras_json
    process_camera(
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_data.py", line 349, in process_camera
    "image_width": image_width,
UnboundLocalError: local variable 'image_width' referenced before assignment
```

**Comment by andrew-codes** [comment]
Upgrading HA to 2021.6.3 seems to have resolved this for me; closing.
